---
title: "Disease Mapping Aragón"
author: "Julián Guilló"
date: "27/10/2021"
output:
  html_document:
    df_print: paged
    keep_md: true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE,
                      message = FALSE,
                      warning = FALSE)
```

## 1. Lectura y preparación de los datos

```{r warning=FALSE}
## Librerías
# operaciones con tablas
library(dplyr)
# lectura y tratamiento de datos geoespaciales
library(sf)
library(spdep)
# modelos bayesianos
library(R2WinBUGS)
# representación gráfica
library(ggplot2)
library(leaflet)
```

```{r}
# Cargamos los datos con info por municipio
load(file.path("datos", "Aragon.Rdata"))
datos <- Aragon.df

# Leemos los datos georeferenciamos y los unimos con los datos cargados previamente
mapa <- read_sf(file.path("datos", "aragon.shp")) %>%
  left_join(datos, by = "CODMUNI") %>%
  mutate(RME = O / E)
```


```{r}
ggplot(mapa) +
  geom_sf(aes(fill = RME)) +
  scale_fill_viridis_c()
```

Vamos a preparar la estructura de vecindad:

```{r}
# Generamos estructura de vecindad
vecinos <- poly2nb(mapa) %>%
  nb2WB()
```



```{r}
# Modelo de regresión de 
```


















```{r}

## Mapa interactivo con librería leaflet
mapa <- st_set_crs(mapa, 25830) # añade el sistema de coordenadas de referencia correcto
mapa <- st_transform(mapa, 4326) # cambiarlo por el que usa leaflet
```


```{r}

paleta <- colorNumeric("RdYlGn", domain = mapa$RME, reverse = TRUE)

labels <- sprintf("<strong> %s </strong> <br/>
  Observados: %s <br/> Esperados: %s <br/>
  RME: %s",
  mapa$NOMBRE, mapa$O, round(mapa$E, 2), round(mapa$RME, 2)
) %>%
  lapply(htmltools::HTML)

leaflet(mapa) %>%
  addTiles() %>%
  addPolygons(
    color = "black", fillColor = ~ paleta(RME),
    fillOpacity = 0.7,
    weight = 1,
    highlightOptions = highlightOptions(
      weight = 3,
      color = "red",
      fillOpacity = 1,
      bringToFront = TRUE),
    label = labels,
    labelOptions = labelOptions(
      style = list(
        "font-weight" = "normal",
        padding = "3px 8px"
      ),
      textsize = "15px", direction = "auto"
    )
  ) %>%
  addLegend(pal = paleta, values = ~RME, opacity = 1)
```

